apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "godzilla.fullname" . }}-manager-role
  labels:
  {{- include "godzilla.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm-chaos.io
  resources:
  - godzillajobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm-chaos.io
  resources:
  - godzillajobs/finalizers
  verbs:
  - update
- apiGroups:
  - helm-chaos.io
  resources:
  - godzillajobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helm-chaos.io
  resources:
  - godzillajobsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm-chaos.io
  resources:
  - godzillajobsnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - helm-chaos.io
  resources:
  - godzillajobsnapshots/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "godzilla.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: godzilla-operator
    app.kubernetes.io/part-of: godzilla-operator
  {{- include "godzilla.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "godzilla.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "godzilla.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'