apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "godzilla-chaos.io/v1alpha1",
          "kind": "GodzillaJob",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "godzilla-operator",
              "app.kubernetes.io/instance": "godzillajob-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "godzillajob",
              "app.kubernetes.io/part-of": "godzilla-operator"
            },
            "name": "godzillajob-sample",
            "namespace": "godzilla-operator-system"
          },
          "spec": {
            "steps": [
              [
                {
                  "config": {
                    "APP_LABEL": "app=debug",
                    "APP_NAMESPACE": "godzilla-operator-system",
                    "CONTAINER_RUNTIME": "docker",
                    "CPU_CORES": "0",
                    "CPU_LOAD": "8",
                    "PODS_AFFECTED_PERC": "100",
                    "SOCKET_PATH": "/var/run/docker.sock",
                    "TOTAL_CHAOS_DURATION": "1200"
                  },
                  "name": "test-pod-disk-io",
                  "type": "litmus-pod-cpu-stress"
                }
              ]
            ]
          }
        },
        {
          "apiVersion": "godzilla-chaos.io/v1alpha1",
          "kind": "GodzillaJobSnapshot",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "godzilla-operator",
              "app.kubernetes.io/instance": "godzillajobsnapshot-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "godzillajobsnapshot",
              "app.kubernetes.io/part-of": "godzilla-operator"
            },
            "name": "godzillajobsnapshot-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-01-03T02:36:20Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: godzilla-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: GodzillaJob is the Schema for the godzillajobs API
      displayName: Godzilla Job
      kind: GodzillaJob
      name: godzillajobs.godzilla-chaos.io
      version: v1alpha1
    - description: GodzillaJobSnapshot is the Schema for the godzillajobsnapshots
        API
      displayName: Godzilla Job Snapshot
      kind: GodzillaJobSnapshot
      name: godzillajobsnapshots.godzilla-chaos.io
      version: v1alpha1
  description: godzilla-operator
  displayName: godzilla-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - godzilla-chaos.io
          resources:
          - godzillajobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - godzilla-chaos.io
          resources:
          - godzillajobs/finalizers
          verbs:
          - update
        - apiGroups:
          - godzilla-chaos.io
          resources:
          - godzillajobs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - godzilla-chaos.io
          resources:
          - godzillajobsnapshots
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - godzilla-chaos.io
          resources:
          - godzillajobsnapshots/finalizers
          verbs:
          - update
        - apiGroups:
          - godzilla-chaos.io
          resources:
          - godzillajobsnapshots/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: godzilla-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: godzilla-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: godzilla-operator
          control-plane: controller-manager
        name: godzilla-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: godzilla-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: godzilla-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - chaos
  links:
  - name: Godzilla Operator
    url: https://godzilla-operator.domain
  maintainers:
  - email: dzhang87@outlook.com
    name: kbfu
  maturity: alpha
  provider:
    name: godzilla
  version: 0.0.1
