apiVersion: v1
kind: ServiceAccount
metadata:
  name: godzilla-operator-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: godzilla-operator
    app.kubernetes.io/part-of: godzilla-operator
  {{- include "godzilla.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}