# permissions for end users to edit godzillajobsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: godzillajobsnapshot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: godzilla-operator
    app.kubernetes.io/part-of: godzilla-operator
    app.kubernetes.io/managed-by: kustomize
  name: godzillajobsnapshot-editor-role
rules:
- apiGroups:
  - charts-chaos.io
  resources:
  - godzillajobsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts-chaos.io
  resources:
  - godzillajobsnapshots/status
  verbs:
  - get
