apiVersion: godzilla-chaos.io/v1alpha1
kind: GodzillaJob
metadata:
  labels:
    app.kubernetes.io/name: godzillajob
    app.kubernetes.io/instance: godzillajob-sample
    app.kubernetes.io/part-of: godzilla-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: godzilla-operator
  name: godzillajob-sample
  namespace: godzilla-operator-system
spec:
  steps:
    - - type: litmus-pod-io-stress
        name: test-pod-disk-io
        config:
          TOTAL_CHAOS_DURATION: '600'
          APP_LABEL: app=debug
          APP_NAMESPACE: godzilla-operator-system
          PODS_AFFECTED_PERC: '100'
          APP_CONTAINER: ''
          CONTAINER_RUNTIME: docker
          SOCKET_PATH: /var/run/docker.sock
          FILESYSTEM_UTILIZATION_BYTES: '40'
          NUMBER_OF_WORKERS: '4'
          VOLUME_MOUNT_PATH: /