apiVersion: godzilla-chaos.io/v1alpha1
kind: GodzillaJob
metadata:
  labels:
    app.kubernetes.io/name: godzillajob
    app.kubernetes.io/instance: godzillajob-sample
    app.kubernetes.io/part-of: godzilla-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: godzilla-operator
  name: godzillajob-sample
  namespace: godzilla-operator-system
spec:
  steps:
    - - name: kill-container
        type: litmus-container-kill
        config:
          TOTAL_CHAOS_DURATION: '30'
          PODS_AFFECTED_PERC: '100'
          APP_NAMESPACE: test-chaos
          APP_LABEL: app=debug
          TARGET_PODS: 'debug-89dbbcf54-dvt46'
          APP_CONTAINER: ''
          CONTAINER_RUNTIME: docker
          SOCKET_PATH: /var/run/docker.sock
          SIGNAL: SIGKILL
        image: wxt432/chaos-go-runner:latest
        serviceAccountName: chaos-admin