apiVersion: godzilla-chaos.io/v1alpha1
kind: GodzillaJob
metadata:
  labels:
    app.kubernetes.io/name: godzillajob
    app.kubernetes.io/instance: godzillajob-sample
    app.kubernetes.io/part-of: godzilla-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: godzilla-operator
  name: godzillajob-sample
  namespace: godzilla-operator-system
spec:
  steps:
    - - type: godzilla-pod-disk-fill
        name: test
        config:
          APP_NAMESPACE: godzilla-operator-system
          TOTAL_CHAOS_DURATION: '600'
          APP_LABEL: app=debug