name: Release Charts

on:
  push:
    branches:
      - gh-pages

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "kbfu"
          git config user.email "d.zeta@163.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: .
          charts_repo_url: https://<owner>.github.io/helm-charts
        env:
          CR_TOKEN: "${{ secrets.TOKEN }}"
